spring:
 profiles:
   active:
   - dev
---
spring:
  profiles: dev     #开发环境
  application:
    name: microservicecloud-config-atguigu-dev3
sun： abc
---
spring:
  profiles: test #测试环境
  application:
   name: microservicecloud-config-atguigu-test3
   
# 必须保存为UTF-8
